let availabledata = [
  {
    name: "Web Programming",
    code: "BCSE203E ",
    capacity: 200,
    credits: 2,
    graded: true,
  },
  {
    name: "Design and Analysis",
    code: "BCSE204L  ",
    capacity: 150,
    credits: 3,
    graded: true,
  },
  {
    name: "Theory of Computation",
    code: "BCSE304L  ",
    capacity: 250,
    credits: 3,
    graded: true,
  },
  {
    name: "Quantitative Skills Practice",
    code: "BSTS102P  ",
    capacity: 100,
    credits: 1.5,
    graded: false,
  },
]; //is also known as all courses
//Student registered data
let studentData = [
  {
    studentName: "John Doe",
    registrationNumber: "REG001",
    Slot: "A1",
    credits: 2,
    courseName: "Web Programming",
    courseCode: "BCSE203E ",
    graded: true,
  },
  {
    studentName: "John Doe",
    registrationNumber: "REG001",
    Slot: "A2",
    credits: 1.5,
    courseName: "Quantitative Skills Practice",
    courseCode: "BSTS101P ",
    graded: false,
  },
  {
    studentName: "John Doe",
    registrationNumber: "REG001",
    Slot: "A2",
    credits: 2,
    courseName: "Design and Analysis",
    courseCode: "BCSE204L  ",
    graded: true,
  },
  {
    studentName: "Jane Smith",
    registrationNumber: "REG002",
    Slot: "B2",
    credits: 1.5,
    courseName: "Quantitative Skills Practice",
    courseCode: "BSTS101P ",
    graded: false,
  },
  {
    studentName: "Alice Johnson",
    registrationNumber: "REG003",
    Slot: "C1",
    credits: 2,
    courseName: "Design and Analysis",
    courseCode: "BCSE204L  ",
    graded: true,
  },
  {
    studentName: "Bob Anderson",
    registrationNumber: "REG004",
    Slot: "D2",
    credits: 2,
    courseName: "Theory of Computation",
    courseCode: "BCSE304L  ",
    graded: true,
  },
  {
    studentName: "Emily Brown",
    registrationNumber: "REG005",
    Slot: "E1",
    credits: 2,
    courseName: "Web Programming",
    courseCode: "BCSE203E ",
    graded: true,
  },
  {
    studentName: "Michael Wilson",
    registrationNumber: "REG006",
    Slot: "F2",
    credits: 1.5,
    courseName: "Quantitative Skills Practice",
    courseCode: "BSTS101P ",
    graded: false,
  },
  {
    studentName: "Sophia Martinez",
    registrationNumber: "REG007",
    Slot: "G1",
    credits: 2,
    courseName: "Theory of Computation",
    courseCode: "BCSE304L  ",
    graded: true,
  },
  {
    studentName: "William Taylor",
    registrationNumber: "REG008",
    Slot: "H2",
    credits: 2,
    courseName: "Design and Analysis",
    courseCode: "BCSE204L  ",
    graded: true,
  },
  {
    studentName: "Olivia Garcia",
    registrationNumber: "REG009",
    Slot: "I1",
    credits: 2,
    courseName: "Web Programming",
    courseCode: "BCSE203E ",
    graded: true,
  },
  {
    studentName: "Daniel Rodriguez",
    registrationNumber: "REG010",
    Slot: "J2",
    credits: 1.5,
    courseName: "Quantitative Skills Practice",
    courseCode: "BSTS101P ",
    graded: false,
  },
  {
    studentName: "Ava Stewart",
    registrationNumber: "REG018",
    Slot: "K1",
    credits: 2,
    courseName: "Theory of Computation",
    courseCode: "BCSE304L  ",
    graded: true,
  },
  {
    studentName: "Ethan Hernandez",
    registrationNumber: "REG012",
    Slot: "L2",
    credits: 2,
    courseName: "Design and Analysis",
    courseCode: "BCSE204L  ",
    graded: true,
  },
  {
    studentName: "Mia Martinez",
    registrationNumber: "REG013",
    Slot: "M1",
    credits: 2,
    courseName: "Web Programming",
    courseCode: "BCSE203E ",
    graded: true,
  },
  {
    studentName: "James Perez",
    registrationNumber: "REG014",
    Slot: "N2",
    credits: 1.5,
    courseName: "Quantitative Skills Practice",
    courseCode: "BSTS101P ",
    graded: false,
  },
  {
    studentName: "Alexander Gomez",
    registrationNumber: "REG015",
    Slot: "O1",
    credits: 2,
    courseName: "Theory of Computation",
    courseCode: "BCSE304L  ",
    graded: true,
  },
  {
    studentName: "Charlotte Campbell",
    registrationNumber: "REG016",
    Slot: "P2",
    credits: 2,
    courseName: "Design and Analysis",
    courseCode: "BCSE204L  ",
    graded: true,
  },
  {
    studentName: "David Robinson",
    registrationNumber: "REG017",
    Slot: "Q1",
    credits: 2,
    courseName: "Web Programming",
    courseCode: "BCSE203E ",
    graded: true,
  },
  {
    studentName: "Ava Stewart",
    registrationNumber: "REG018",
    Slot: "R2",
    credits: 1.5,
    courseName: "Quantitative Skills Practice",
    courseCode: "BSTS101P ",
    graded: false,
  },
  {
    studentName: "Joseph Phillips",
    registrationNumber: "REG019",
    Slot: "S1",
    credits: 2,
    courseName: "Theory of Computation",
    courseCode: "BCSE304L  ",
    graded: true,
  },
  {
    studentName: "Emma Evans",
    registrationNumber: "REG020",
    Slot: "T2",
    credits: 2,
    courseName: "Design and Analysis",
    courseCode: "BCSE204L  ",
    graded: true,
  },
];

let AllCourses = [
  "Web Programming",
  "Design and Analysis",
  "Theory of Computation",
  "Quantitative Skills Practice",
];
let AllCoursesKeyValuePair = {
  "Web Programming": "BCSE203E ",
  "Design and Analysis": "BCSE204L  ",
  "Theory of Computation": "BCSE304L  ",
  "Quantitative Skills Practice": "BSTS101P ",
};
let AvaStewartRegisteredCourses = studentData.filter((item) => {
  if (item.studentName == "Ava Stewart") {
    return item;
  }
});

let AvaStewartCompletedCourses = [
  {
    courseName: "Introduction to Psychology",
    courseCode: "BPSY101E",
    creditsEarned: 2,
    grade: "A",
  },
  {
    courseName: "Data Structures and Algorithms",
    courseCode: "BCSE201L",
    creditsEarned: 3,
    grade: "S",
  },
  {
    courseName: "English Composition",
    courseCode: "BENG102E",
    creditsEarned: 2,
    grade: "B",
  },
  {
    courseName: "Microeconomics",
    courseCode: "BECO202L",
    creditsEarned: 4,
    grade: "B",
  },
];

let paymentRegisteredCourses = [];
